version: '3.7'

services:
  
  teste:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/deploy.sh"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - default
    
networks:
  default:
    name: desafio
    driver: bridge