version: '3.7'

services:
  
  api:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    ports:
      - 8082
      
  test:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/test.sh"]
    
  deploy:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/deploy.sh"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}